### ISSUE TITLE
Chapter text should display without js.

### ISSUE THREAD

**Issue by nanodesutl** [NanoDesuTranslations/MockV1#5]
Currently the site does not show text without js.
![untitled](https://cloud.githubusercontent.com/assets/15543917/16028061/42e6fe06-3190-11e6-8f63-50dbab617c61.png)

**Comment by DerekRS** [comment]
There are new static pages that should show content even if you have script turned off.

JavaScript is being used in this mock so that it can show changing content as you change "chapter" pages and different table of contents as you change "series"--all without needing back end server code.  If you don't happen to need that functionality, by all means use the static pages.
